
services:
  uz_movie:
    build: ./
    container_name: "uz_movie"
    command: /uz_movie/entrypoint.sh
    restart: always
    volumes:
      - .:/uz_movie
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - uz_movie_db

  uz_movie_db:
    image: postgres:16
    container_name: "uz_movie_db"
    volumes:
      - postgres_data_uz_movie_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5434:5432

volumes:
  postgres_data_uz_movie_db: