version: '3.9'

services:
  uz_movie:
    build: ./
    container_name: "uz_movie"
    command: /uz_movie/entrypoint.sh
    restart: always
    volumes:
      - .:/uz_movie
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - uz_movie_db

  uz_movie_db:
    image: postgres:16
    container_name: "uz_movie_db"
    volumes:
      - postgres_data_uz_movie_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5434:5432

  uz_movie_minio:
    image: minio/minio
    container_name: "uz_movie_minio"
    ports:
      - 9009:9009
      - 9099:9099
    volumes:
      - uz_movie_minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin:admin
      MINIO_ROOT_PASSWORD: admin:admin
    command: server --console-address ":9099" /data

volumes:
  uz_movie_minio_storage:
  postgres_data_uz_movie_db: